#!/bin/sh -f
# $Id: metrics,v 1.3 2003/02/11 17:52:21 myke Exp $

if [ $# -lt 1 ] ;
then
    echo "Usage: `basename $0` <dir1> [dir2 ...]"
    exit
fi

while [ $# -ge 1 ] ; 
do
    if [ ! -d $1 ] ;
    then
	echo "<$1> not a directory"
	shift
	continue
    fi

    echo "--------- Metrics for $1 ---------"
    find $1 -name '*.[ch]pp' -print -o -name '*.[ch]' -print -o \
	    -name '*.cc' -print | xargs metrics.awk | grep '^Total' | \
	    awk '/lines/ {lines+=$4;} \
	         /comment/ {comments+=$5;} \
		 END { if (lines > 0) { \
		         printf("Total lines         = %d\n"\
			        "Total comment lines = %d\n"\
			        "Comments to lines   = %%%.2f\n", \
		 	         lines, comments, 100.0 * comments / lines);\
                       } \
		       else { \
		         printf("No code lines found.\n"); \
		       } \
                     }'
    shift
done